// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/preview/image/:imageId.bytes": {
    params: {
      "imageId": string;
    };
  };
  "/preview/effie/:effieId.json": {
    params: {
      "effieId": string;
    };
  };
  "/preview/annie/:annieId.tar": {
    params: {
      "annieId": string;
    };
  };
  "/preview/annie/:annieId": {
    params: {
      "annieId": string;
    };
  };
  "/preview/effie/:effieId": {
    params: {
      "effieId": string;
    };
  };
  "/preview/image/:imageId": {
    params: {
      "imageId": string;
    };
  };
  "/annie/:segment": {
    params: {
      "segment": string;
    };
  };
  "/effie/:segment": {
    params: {
      "segment": string;
    };
  };
  "/image/:segment": {
    params: {
      "segment": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/preview/image/:imageId.bytes" | "/preview/effie/:effieId.json" | "/preview/annie/:annieId.tar" | "/preview/annie/:annieId" | "/preview/effie/:effieId" | "/preview/image/:imageId" | "/annie/:segment" | "/effie/:segment" | "/image/:segment";
  };
  "routes/preview.image.$imageId[.bytes].tsx": {
    id: "routes/preview.image.$imageId[.bytes]";
    page: "/preview/image/:imageId.bytes";
  };
  "routes/preview.effie.$effieId[.json].tsx": {
    id: "routes/preview.effie.$effieId[.json]";
    page: "/preview/effie/:effieId.json";
  };
  "routes/preview.annie.$annieId[.tar].tsx": {
    id: "routes/preview.annie.$annieId[.tar]";
    page: "/preview/annie/:annieId.tar";
  };
  "routes/preview.annie.$annieId.tsx": {
    id: "routes/preview.annie.$annieId";
    page: "/preview/annie/:annieId";
  };
  "routes/preview.effie.$effieId.tsx": {
    id: "routes/preview.effie.$effieId";
    page: "/preview/effie/:effieId";
  };
  "routes/preview.image.$imageId.tsx": {
    id: "routes/preview.image.$imageId";
    page: "/preview/image/:imageId";
  };
  "routes/annie.$segment.tsx": {
    id: "routes/annie.$segment";
    page: "/annie/:segment";
  };
  "routes/effie.$segment.tsx": {
    id: "routes/effie.$segment";
    page: "/effie/:segment";
  };
  "routes/image.$segment.tsx": {
    id: "routes/image.$segment";
    page: "/image/:segment";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/preview.image.$imageId[.bytes]": typeof import("./app/routes/preview.image.$imageId[.bytes].tsx");
  "routes/preview.effie.$effieId[.json]": typeof import("./app/routes/preview.effie.$effieId[.json].tsx");
  "routes/preview.annie.$annieId[.tar]": typeof import("./app/routes/preview.annie.$annieId[.tar].tsx");
  "routes/preview.annie.$annieId": typeof import("./app/routes/preview.annie.$annieId.tsx");
  "routes/preview.effie.$effieId": typeof import("./app/routes/preview.effie.$effieId.tsx");
  "routes/preview.image.$imageId": typeof import("./app/routes/preview.image.$imageId.tsx");
  "routes/annie.$segment": typeof import("./app/routes/annie.$segment.tsx");
  "routes/effie.$segment": typeof import("./app/routes/effie.$segment.tsx");
  "routes/image.$segment": typeof import("./app/routes/image.$segment.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
};